### PR TITLE
DTPORTAL-16979 Fix audio corruption: UniMRCP quick-fix

### PR DESCRIPTION
**Pull request by sfgeorge**
## [DTPORTAL-16979 Fix audio corruption: UniMRCP quick-fix](https://dialogtech.atlassian.net/browse/DTPORTAL-16979)

Fix the audio corruption issue by addressing the garbage-in / garbage-out problem; make sure that UniMRCP sends data to Asterisk 20ms at a time instead of 10ms at a time.

In the absence of Asterisk's chan_sip driver from properly setting up an RTP smoother / outbound jitter buffer, sending packets 20ms at a time is the next-best thing.

This change will _not_ be submitted to the upstream UniMRCP project because this is not truly the right way to solve this problem – but it gets the job done in the immediate for us.

### CODE REVIEW

**Comment by sfgeorge** [comment]
@dasbus Can you review this for me?

Cc: @gfaza @jbuehring

**Review by dasbus — APPROVED** [review]
👍 
Curious, does this need to be or should be reverted when we move to PJ SIP?

**Comment by sfgeorge** [comment]
@dasbus Excellent q.  It doesn't need to be immediately reverted when we move to PJ SIP, at that point this change will be harmless but unnecessary.

The only downside of this change is that it deviates us from the official unimrcp project in a way that can't be adopted upstream.  So, the moment we are on PJ SIP and there is a new shiny release of UniMRCP that we want to take advantage of, the nice thing then will be to be able to swap to the official release and abandon our fork.

**Comment by jbuehring** [comment]
If this is the basis for the built `1.6.0-15.dt_2` RPM, we can merge this.

CC @gfaza

**Comment by sfgeorge** [comment]
@jbuehring @gfaza @dasbus I _believe_ if I recall correctly that the unimrcp rpm packages that are built in the private stockyard repo include the git commit SHA somewhere in the package metadata.

If you hop onto a box that has version `1.6.0-15.dt_2` installed, and then run `rpm -qi unimrcp`, then it should hopefully report which git sha of unimrcp was used to build that rpm.  Let me know if there's anything puzzling that remains, happy to help.

**Comment by jbuehring** [comment]
@sfgeorge Totally didn't expect you to reply here!  It turns out, `1.6.0-15.dt_2` is built from https://github.com/cloudvox/unimrcp/pull/1/commits/e69f66c97675345e34866cfe88b07f5a2f52ca5b.  Essentially the same change, just a different PR.

**Pull request merged**
